Cadayona/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('', include('rolo.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rolo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_page, name="homePage"),
    path('about/', views.about_page, name="aboutPage"),
    path('contact/', views.contact_page, name="contactPage"),
    path('services/', views.services_page, name="servicesPage"),
    path('login/', views.login_page, name="loginPage"),
    path('register/', views.register_page, name="registerPage"),
    path('create/', views.create_garment_schedule_payment, name='create_garment_schedule_payment'),
    path('dashboard/', views.dashboard_page, name='dashboard'),
    path('update/<int:garment_id>/', views.update_garment_schedule_payment, name='update_garment_schedule_payment'),
    path('delete/<int:garment_id>/', views.delete_garment, name='delete_garment'),
    path('display/<int:garment_id>/', views.display_garment, name='display_garment'),

]

rolo/models.py
from django.core.validators import MinValueValidator
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    middle_initial = models.CharField(max_length=50, null=True)
    address = models.CharField(max_length=255, null=True)
    contact = models.IntegerField()
    email = models.EmailField(max_length=255, null=True)
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True)

    def __str__(self):
        return self.user


class Garment(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    type = models.CharField(max_length=255)
    quantity = models.PositiveIntegerField(validators=[MinValueValidator(0)])

    def __str__(self):
        return self.name


class Schedule(models.Model):
    garment = models.OneToOneField(Garment, on_delete=models.CASCADE, related_name='schedule')
    date = models.DateField()
    time = models.TimeField()
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.garment


class Payment(models.Model):
    garment = models.OneToOneField(Garment, on_delete=models.CASCADE, related_name='payment')
    amount = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    payment_date = models.DateTimeField(auto_now_add=True, null=True)

    STATUS_CHOICES = [
        ('Unpaid', 'Unpaid'),
        ('Paid', 'Paid'),
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Pending')

    MODE_CHOICES = [
        ('CreditCard', 'Credit Card'),
        ('DebitCard', 'Debit Card'),
        ('BankTransfer', 'Bank Transfer'),
        ('Cash', 'Cash'),
        # Add more choices as needed
    ]
    mode_of_payment = models.CharField(max_length=20, choices=MODE_CHOICES, default='CreditCard')

    def __str__(self):
        return self.amount

rolo/forms.py
from django import forms
from django.core.validators import MinValueValidator

from .models import Garment, Payment


class GarmentSchedulePaymentForm(forms.ModelForm):
    class Meta:
        model = Garment
        fields = ['name', 'description', 'type', 'quantity']

    quantity = forms.IntegerField(validators=[MinValueValidator(0)])
    date = forms.DateField()
    time = forms.TimeField()
    amount = forms.DecimalField(max_digits=10, decimal_places=2)
    status = forms.ChoiceField(choices=Payment.STATUS_CHOICES, initial='Pending')
    mode_of_payment = forms.ChoiceField(choices=Payment.MODE_CHOICES, initial='CreditCard')

rolo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Garment, Schedule, Payment
from .forms import GarmentSchedulePaymentForm


def home_page(request):
    # return HttpResponse("HI THis is ROlO homepage")
    return render(request, 'pages/home.html')


def about_page(request):
    # return HttpResponse("This is aboutpage")
    return render(request, 'pages/about.html')


def contact_page(request):
    # return HttpResponse("This is contactpage")
    return render(request, 'pages/contact.html')


def services_page(request):
    # return HttpResponse("This is services")
    return render(request, 'pages/services.html')


def login_page(request):
    return render(request, 'pages/login.html')


def register_page(request):
    return render(request, 'pages/register.html')


def dashboard_page(request):
    garments = Garment.objects.all()
    return render(request, 'pages/dashboard.html', {'garments': garments})


def create_garment_schedule_payment(request):
    if request.method == 'POST':
        form = GarmentSchedulePaymentForm(request.POST)
        if form.is_valid():
            garment = form.save(commit=False)
            garment.save()

            schedule = Schedule.objects.create(
                garment=garment,
                date=form.cleaned_data['date'],
                time=form.cleaned_data['time']
            )

            Payment.objects.create(
                garment=garment,
                amount=form.cleaned_data['amount'],
                status=form.cleaned_data['status'],
                mode_of_payment=form.cleaned_data['mode_of_payment']
            )

            return redirect('dashboard')  # Redirect to your dashboard page
    else:
        form = GarmentSchedulePaymentForm()

    return render(request, 'pages/repairForm.html', {'form': form})


def update_garment_schedule_payment(request, garment_id):
    garment = get_object_or_404(Garment, pk=garment_id)
    schedule = garment.schedule
    payment = garment.payment

    if request.method == 'POST':
        form = GarmentSchedulePaymentForm(request.POST, instance=garment)
        if form.is_valid():
            garment = form.save(commit=False)
            garment.save()

            schedule.date = form.cleaned_data['date']
            schedule.time = form.cleaned_data['time']
            schedule.save()

            payment.amount = form.cleaned_data['amount']
            payment.status = form.cleaned_data['status']
            payment.mode_of_payment = form.cleaned_data['mode_of_payment']
            payment.save()

            return redirect('dashboard')  # Redirect to your dashboard page
    else:
        form = GarmentSchedulePaymentForm(instance=garment)

    return render(request, 'pages/repairForm.html', {'form': form, 'garment': garment})


def delete_garment(request, garment_id):
    garment = get_object_or_404(Garment, pk=garment_id)
    garment.delete()
    return redirect('dashboard')  # Redirect to your dashboard page


def display_garment(request, garment_id):
    garment = get_object_or_404(Garment, pk=garment_id)
    return render(request, 'pages/displayGarment.html', {'garment': garment})

rolo/templates/pages/dashboard.html
{% extends 'pages/index.html' %}
{% load static %}
{% block content %}
<div class="bg-cyan-800">
<h1 class="p-7 text-white text-4xl uppercase text-bold border-b-4 border-cyan-950">Dashboard</h1>

    <a href="{% url 'create_garment_schedule_payment' %}" class="bg-info text-black py-3 px-5 m-3 rounded-lg">Create Services</a>
    <a href="#" class="bg-info text-black py-3 px-5 m-3 rounded-lg">Manage Schedules</a>
</div>
<div class="bg-cyan-800">
    <h1 class="p-5 text-white text-xl">Record of Repairs</h1>
</div>
{% for garment in garments %}
    <div class="flex bg-cyan-950 space-x-4 pl-5 py-5 ">
        <h2>{{ garment.name }}</h2>
        <p>Description: {{ garment.description }}</p>
        <p>Type: {{ garment.type }}</p>
        <p>Quantity: {{ garment.quantity }}</p>
        <p>Date: {{ garment.schedule.date }}</p>
        <p>Time: {{ garment.schedule.time }}</p>
        <p>Amount: {{ garment.payment.amount }}</p>
        <p>Status: {{ garment.payment.get_status_display }}</p>
        <p>Mode of Payment: {{ garment.payment.get_mode_of_payment_display }}</p>
        <a href="{% url 'display_garment' garment.id %}" class="p-2 hover:text-cyan-600 text-info hover:text-xl uppercase">View Details</a>
        <a href="{% url 'update_garment_schedule_payment' garment.id %}" class="p-2 hover:text-cyan-600 text-warning hover:text-xl uppercase">Edit</a>
        <a href="{% url 'delete_garment' garment.id %}" class="p-2 hover:text-cyan-600 text-danger hover:text-xl uppercase">Delete</a>
    </div>
{% endfor %}

{% endblock %}

rolo/templates/pages/displayGarment.html
{% extends 'pages/index.html' %}
{% load static %}
{% block content %}
<div class="bg-cyan-950">
    <h1 class="pt-14 pl-10 text-white text-4xl uppercase text-bold border-b-4 border-cyan-950">User Booked Information</h1>

    <div class="ml-32 py-10 text-lg">
    <h2>Name: {{ garment.name }}</h2>
    <p>Description: {{ garment.description }}</p>
    <p>Type: {{ garment.type }}</p>
    <p>Quantity: {{ garment.quantity }}</p>
    <p>Scheduled Date: {{ garment.schedule.date }}</p>
    <p>Scheduled Time: {{ garment.schedule.time }}</p>
    <p>Services Created: {{ garment.schedule.date_created }}</p>
    <p>Amount: {{ garment.payment.amount }}</p>
    <p>Status: {{ garment.payment.get_status_display }}</p>
    <p>Mode of Payment: {{ garment.payment.get_mode_of_payment_display }}</p>
    <a href="{% url 'update_garment_schedule_payment' garment.id %}" class="p-2 hover:text-cyan-600 text-warning hover:text-xl uppercase">Edit</a>
    <a href="{% url 'delete_garment' garment.id %}" class="p-2 hover:text-cyan-600 text-danger hover:text-xl  uppercase">Delete</a>
    <a href="{% url 'dashboard' %}" class="p-2 hover:text-cyan-600 text-info hover:text-xl  uppercase">Dashboard</a>
</div>

</div>



{% endblock %}

rolo/templates/pages/footer.html
<!-- Footer container -->
<footer
  class="bg-neutral-100 text-center text-neutral-600 dark:bg-neutral-600 dark:text-neutral-200 lg:text-left">
  <div
    class="flex items-center justify-center border-b-2 border-neutral-200 p-6 dark:border-neutral-500 lg:justify-between ">
    <div class="mr-12 hidden lg:block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Social network icons container -->
    <div class="flex justify-center">
      <a href="#!" class="mr-6 text-neutral-600 dark:text-neutral-200">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-4 w-4"
          fill="currentColor"
          viewBox="0 0 24 24">
          <path
            d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z" />
        </svg>
      </a>
      <a href="#!" class="mr-6 text-neutral-600 dark:text-neutral-200">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-4 w-4"
          fill="currentColor"
          viewBox="0 0 24 24">
          <path
            d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z" />
        </svg>
      </a>
      <a href="#!" class="mr-6 text-neutral-600 dark:text-neutral-200">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-5 w-5"
          fill="currentColor"
          viewBox="0 0 24 24">
          <path
            d="M7 11v2.4h3.97c-.16 1.029-1.2 3.02-3.97 3.02-2.39 0-4.34-1.979-4.34-4.42 0-2.44 1.95-4.42 4.34-4.42 1.36 0 2.27.58 2.79 1.08l1.9-1.83c-1.22-1.14-2.8-1.83-4.69-1.83-3.87 0-7 3.13-7 7s3.13 7 7 7c4.04 0 6.721-2.84 6.721-6.84 0-.46-.051-.81-.111-1.16h-6.61zm0 0 17 2h-3v3h-2v-3h-3v-2h3v-3h2v3h3v2z"
            fill-rule="evenodd"
            clip-rule="evenodd" />
        </svg>
      </a>
      <a href="#!" class="mr-6 text-neutral-600 dark:text-neutral-200">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-4 w-4"
          fill="currentColor"
          viewBox="0 0 24 24">
          <path
            d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z" />
        </svg>
      </a>
      <a href="#!" class="mr-6 text-neutral-600 dark:text-neutral-200">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-4 w-4"
          fill="currentColor"
          viewBox="0 0 24 24">
          <path
            d="M4.98 3.5c0 1.381-1.11 2.5-2.48 2.5s-2.48-1.119-2.48-2.5c0-1.38 1.11-2.5 2.48-2.5s2.48 1.12 2.48 2.5zm.02 4.5h-5v16h5v-16zm7.982 0h-4.968v16h4.969v-8.399c0-4.67 6.029-5.052 6.029 0v8.399h4.988v-10.131c0-7.88-8.922-7.593-11.018-3.714v-2.155z" />
        </svg>
      </a>
    </div>
  </div>
<!--  <hr class="hrfooter">-->
  <!-- Main container div: holds the entire content of the footer, including four sections (TW elements, Products, Useful links, and Contact), with responsive styling and appropriate padding/margins. -->
  <div class="mx-6 py-10 text-center md:text-left">
    <div class="grid-1 grid gap-8 md:grid-cols-2 lg:grid-cols-4">
      <!-- TW elements section -->
      <div class="">

        <h6 class="mb-4 flex items-center justify-center font-semibold uppercase md:justify-start ">
          <i class="fi fi-rs-building mr-1.5"></i>
          ROLO INC.
        </h6>
        <p>
          ROLO is a website that you can book a repair for your cloth and make also a view to shops product /w a
          new system to make more the user to enquire a repair we make a friendly  simple UI for user to identify the
          things he needs along
        </p>
      </div>
      <!-- Products section -->
      <div class="">
        <h6
          class="mb-4 flex justify-center font-semibold uppercase md:justify-start">
          Pages
        </h6>
        <p class="mb-4">
          <a href="#!" class="text-neutral-600 dark:text-neutral-200"
            >Home</a
          >
        </p>
        <p class="mb-4">
          <a href="#!" class="text-neutral-600 dark:text-neutral-200"
            >AboutUs</a
          >
        </p>
        <p class="mb-4">
          <a href="#!" class="text-neutral-600 dark:text-neutral-200"
            >Contact</a
          >
        </p>
        <p>
          <a href="#!" class="text-neutral-600 dark:text-neutral-200"
            >Services</a
          >
        </p>
      </div>
      <!-- Useful links section -->
      <div class="">
        <h6
          class="mb-4 flex justify-center font-semibold uppercase md:justify-start">
          Support
        </h6>
        <p class="mb-4">
          <a href="#!" class="text-neutral-600 dark:text-neutral-200"
            >FAQs</a
          >
        </p>
        <p class="mb-4">
          <a href="#!" class="text-neutral-600 dark:text-neutral-200"
            >Return Policy</a
          >
        </p>
        <p class="mb-4">
          <a href="#!" class="text-neutral-600 dark:text-neutral-200"
            >Privacy Policy</a
          >
        </p>
        <p>
          <a href="#!" class="text-neutral-600 dark:text-neutral-200"
            >Shipping Terms</a
          >
        </p>
      </div>
      <!-- Contact section -->
      <div>
        <h6
          class="mb-4 flex justify-center font-semibold uppercase md:justify-start">
          Contact
        </h6>
        <p class="mb-4 flex items-center justify-center md:justify-start">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="currentColor"
            class="mr-3 h-5 w-5">
            <path
              d="M11.47 3.84a.75.75 0 011.06 0l8.69 8.69a.75.75 0 101.06-1.06l-8.689-8.69a2.25 2.25 0 00-3.182 0l-8.69 8.69a.75.75 0 001.061 1.06l8.69-8.69z" />
            <path
              d="M12 5.432l8.159 8.159c.03.03.06.058.091.086v6.198c0 1.035-.84 1.875-1.875 1.875H15a.75.75 0 01-.75-.75v-4.5a.75.75 0 00-.75-.75h-3a.75.75 0 00-.75.75V21a.75.75 0 01-.75.75H5.625a1.875 1.875 0 01-1.875-1.875v-6.198a2.29 2.29 0 00.091-.086L12 5.43z" />
          </svg>
          Mt. Mayon, Ph1, Bacoor, Cavite
        </p>
        <p class="mb-4 flex items-center justify-center md:justify-start">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="currentColor"
            class="mr-3 h-5 w-5">
            <path
              d="M1.5 8.67v8.58a3 3 0 003 3h15a3 3 0 003-3V8.67l-8.928 5.493a3 3 0 01-3.144 0L1.5 8.67z" />
            <path
              d="M22.5 6.908V6.75a3 3 0 00-3-3h-15a3 3 0 00-3 3v.158l9.714 5.978a1.5 1.5 0 001.572 0L22.5 6.908z" />
          </svg>
          ROLOPhContact@Gmail.com
        </p>
        <p class="mb-4 flex items-center justify-center md:justify-start">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="currentColor"
            class="mr-3 h-5 w-5">
            <path
              fill-rule="evenodd"
              d="M1.5 4.5a3 3 0 013-3h1.372c.86 0 1.61.586 1.819 1.42l1.105 4.423a1.875 1.875 0 01-.694 1.955l-1.293.97c-.135.101-.164.249-.126.352a11.285 11.285 0 006.697 6.697c.103.038.25.009.352-.126l.97-1.293a1.875 1.875 0 011.955-.694l4.423 1.105c.834.209 1.42.959 1.42 1.82V19.5a3 3 0 01-3 3h-2.25C8.552 22.5 1.5 15.448 1.5 6.75V4.5z"
              clip-rule="evenodd" />
          </svg>
          + 01 234 567 88
        </p>
        <p class="flex items-center justify-center md:justify-start">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="currentColor"
            class="mr-3 h-5 w-5">
            <path
              fill-rule="evenodd"
              d="M7.875 1.5C6.839 1.5 6 2.34 6 3.375v2.99c-.426.053-.851.11-1.274.174-1.454.218-2.476 1.483-2.476 2.917v6.294a3 3 0 003 3h.27l-.155 1.705A1.875 1.875 0 007.232 22.5h9.536a1.875 1.875 0 001.867-2.045l-.155-1.705h.27a3 3 0 003-3V9.456c0-1.434-1.022-2.7-2.476-2.917A48.716 48.716 0 0018 6.366V3.375c0-1.036-.84-1.875-1.875-1.875h-8.25zM16.5 6.205v-2.83A.375.375 0 0016.125 3h-8.25a.375.375 0 00-.375.375v2.83a49.353 49.353 0 019 0zm-.217 8.265c.178.018.317.16.333.337l.526 5.784a.375.375 0 01-.374.409H7.232a.375.375 0 01-.374-.409l.526-5.784a.373.373 0 01.333-.337 41.741 41.741 0 018.566 0zm.967-3.97a.75.75 0 01.75-.75h.008a.75.75 0 01.75.75v.008a.75.75 0 01-.75.75H18a.75.75 0 01-.75-.75V10.5zM15 9.75a.75.75 0 00-.75.75v.008c0 .414.336.75.75.75h.008a.75.75 0 00.75-.75V10.5a.75.75 0 00-.75-.75H15z"
              clip-rule="evenodd" />
          </svg>
          + 01 234 567 89
        </p>
      </div>
    </div>
  </div>

  <!--Copyright section-->
  <div class="bg-cyan-950 p-6 text-center dark:bg-neutral-700 ">
    <span class="text-white">  Copyright © 2023</span>
    <a
      class="font-semibold text-white dark:text-neutral-400"
      href="#"
      >ROLO, INC.</a
    >
  </div>
</footer>

rolo/templates/pages/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ROLO</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--  Favicon link  -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static '/images/favicon.png'%}">
    <!--  CSS link  -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!--  Flaticon link  -->
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.0.0/uicons-regular-rounded/css/uicons-regular-rounded.css'>
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.0.0/uicons-regular-straight/css/uicons-regular-straight.css'>
    <!-- CDN for tailwindCss -->
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
    <!-- CDN for AOS Transitions -->
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
         AOS.init();
    </script>
    <!--  CDN for TW elements  -->
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900&display=swap"
      rel="stylesheet" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/tw-elements/dist/css/tw-elements.min.css" />
    <script src="https://cdn.tailwindcss.com/3.3.0"></script>
    <script>
      tailwind.config = {
        darkMode: "class",
        theme: {
          fontFamily: {
            sans: ["Roboto", "sans-serif"],
            body: ["Roboto", "sans-serif"],
            mono: ["ui-monospace", "monospace"],
          },
        },
        corePlugins: {
          preflight: false,
        },
      };
    </script>

    <!-- END link  -->
</head>
<body>
<script>
         AOS.init();
    </script>
 {% include 'pages/navbar.html' %}

<!--<h1 style="text-align: center">homepage Section of ROLO</h1>-->

    {%block content%}
        {#home#}
    {%endblock%}

<hr>
<!--<h1 style="text-align: center">footer Section of ROLO </h1>-->
    {% include 'pages/footer.html' %}

<!-- JavaScript link -->
 <script src="{% static 'js/script.js' %}"></script>
 <script src="{% static 'js/script1.js' %}"></script>
<!-- tw-elements-js  -->
 <script src="https://cdn.jsdelivr.net/npm/tw-elements/dist/js/tw-elements.umd.min.js"></script>
<!-- aos-transitions-js  -->


</body>
</html>

rolo/templates/pages/repairForm.html
{% extends 'pages/index.html' %}
{% load static %}
{% block content %}
<div class="bg-cyan-800 tex-black">
   <form method="POST" action="">
        {% csrf_token %}
       <div class="text-black p-10">
                <h2>Name: {{ form.name }}</h2>
                <p>Description: {{ form.description }}</p>
                <p>Type: {{ form.type }}</p>
                <p>Quantity: {{ form.quantity }}</p>
                <p>Date: {{ form.date }}</p>
                <p>Time: {{ form.time }}</p>
                <p>Amount: {{ form.amount }}</p>
                <p>Status: {{ form.status }}</p>
                <p>Mode of Payment: {{ form.mode_of_payment }}</p>
       </div>
        <div class="">
             <a href="{% url 'homePage' %}" class="bg-warning text-white py-3 px-5 m-3 rounded-lg uppercase ">Cancel</a>
            <input type="submit" name="Submit" class="bg-cyan-950 text-white py-3 px-5 m-3 rounded-lg uppercase" >
        </div>

    </form>
</div>



{% endblock %}